import os
import logging
import asyncio
from fastapi import FastAPI, Request, HTTPException
from fastapi.responses import PlainTextResponse
from dotenv import load_dotenv
import requests
from google.adk.agents import Agent
from google.adk.runners import InMemoryRunner
from google.adk.sessions import InMemorySessionService
from google.adk.tools import google_search
from google.genai import types

load_dotenv()

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI()

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
WHATSAPP_TOKEN = os.getenv("WHATSAPP_TOKEN")
PHONE_NUMBER_ID = os.getenv("PHONE_NUMBER_ID")
VERIFY_TOKEN = os.getenv("VERIFY_TOKEN")

WHATSAPP_API_URL = f"https://graph.facebook.com/v18.0/{PHONE_NUMBER_ID}/messages"

os.environ["GOOGLE_API_KEY"] = GOOGLE_API_KEY
os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "FALSE"

root_agent = Agent(
    name="helpful_assistant",
    model="gemini-2.0-flash-exp",
    description="Helpful AI assistant integrated with WhatsApp that can answer questions and search for current info.",
    instruction="Be concise, helpful, and respond to user messages.",
    tools=[google_search],
)

APP_NAME = "whatsapp_bot"

runner = InMemoryRunner(agent=root_agent, app_name=APP_NAME)
session_service = runner.session_service
sessions = {}

async def get_or_create_session(user_id: str) -> str:
    if user_id not in sessions:
        session = await session_service.create_session(app_name=APP_NAME, user_id=user_id)
        sessions[user_id] = session.id
        logger.info(f"Created new session {session.id} for user {user_id}")
    return sessions[user_id]

async def run_agent(message: str, user_id: str) -> str:
    try:
        logger.info(f"Running AI agent for user {user_id}: {message}")
        session_id = await get_or_create_session(user_id)
        user_message = types.Content(role='user', parts=[types.Part(text=message)])
        events = runner.run_async(user_id=user_id, session_id=session_id, new_message=user_message)
        async for event in events:
            logger.info(f"AI event: {event}")
            if event.is_final_response():
                if event.content and event.content.parts:
                    response_text = event.content.parts[0].text or "No response generated."
                    logger.info(f"Agent response: {response_text}")
                    return response_text
        logger.info("No final response generated by AI")
        return "I received your message but couldn't generate a response."
    except Exception as e:
        logger.error(f"Error in AI agent: {str(e)}")
        return "Sorry, I encountered an error while processing your message."

def send_whatsapp_message(to: str, message: str) -> bool:
    headers = {
        "Authorization": f"Bearer {WHATSAPP_TOKEN}",
        "Content-Type": "application/json"
    }
    payload = {
        "messaging_product": "whatsapp",
        "to": to,
        "type": "text",
        "text": {"body": message}
    }
    try:
        response = requests.post(WHATSAPP_API_URL, json=payload, headers=headers)
        response.raise_for_status()
        logger.info(f"Message sent successfully to {to}")
        return True
    except Exception as e:
        logger.error(f"Error sending WhatsApp message: {str(e)}")
        return False

@app.get("/webhook")
async def verify_webhook(request: Request):
    mode = request.query_params.get("hub.mode")
    token = request.query_params.get("hub.verify_token")
    challenge = request.query_params.get("hub.challenge")
    if mode == "subscribe" and token == VERIFY_TOKEN:
        logger.info("Webhook verified successfully")
        return PlainTextResponse(challenge)
    else:
        logger.warning("Webhook verification failed")
        raise HTTPException(status_code=403, detail="Verification failed")

@app.post("/webhook")
async def receive_message(request: Request):
    try:
        body = await request.json()
        logger.info(f"Webhook hit! Full body: {body}")
        if body.get("object") == "whatsapp_business_account":
            entries = body.get("entry", [])
            for entry in entries:
                changes = entry.get("changes", [])
                for change in changes:
                    value = change.get("value", {})
                    messages = value.get("messages", [])
                    for message in messages:
                        message_type = message.get("type")
                        from_number = message.get("from")
                        message_body = message.get("text", {}).get("body", "")
                        logger.info(f"Received message from {from_number}: {message_body}")
                        if message_type == "text" and message_body.strip():
                            ai_response = await run_agent(message_body, from_number)
                            send_whatsapp_message(from_number, ai_response)
        return {"status": "ok"}
    except Exception as e:
        logger.error(f"Error processing webhook: {str(e)}")
        return {"status": "error", "message": str(e)}

@app.get("/")
async def root():
    return {
        "status": "running",
        "service": "WhatsApp AI Bot",
        "endpoints": {
            "webhook_verify": "GET /webhook",
            "webhook_receive": "POST /webhook"
        }
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8080)